name: Verify existence of CONTRIBUTING.md file

on:
  push:
  pull_request:
  
jobs:
  verify:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          [[ -f CONTRIBUTING.md ]] || ( echo "CONTRIBUTING.md file needs to be added to ${{ github.repository }} !" && exit 1 )
          
      
